<?php
$title = "HTTP 502 Bad Gateway – Upstream Server Errors";
$description = "Technical documentation explaining the HTTP 502 Bad Gateway status code. Learn how gateway servers generate 502 responses and how developers diagnose upstream failures.";
?>

<!DOCTYPE html>
<html lang="en">
<head>

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<title><?php echo $title; ?> | Node403 Docs</title>

<meta name="description" content="<?php echo $description; ?>">
<meta name="robots" content="index, follow">

<link rel="canonical" href="https://node403.com/docs/502.php">

<meta property="og:title" content="<?php echo $title; ?>">
<meta property="og:description" content="<?php echo $description; ?>">
<meta property="og:type" content="article">
<meta property="og:url" content="https://node403.com/docs/doc-502.php">
<link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;500&display=swap" rel="stylesheet">

<link rel="stylesheet" href="style.css">
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-4191744023231140"
     crossorigin="anonymous"></script>
</head>

<body>

<div class="wrapper">

<?php include "templates/header.php"; ?>

<div class="header">

<h1>HTTP 502 Bad Gateway</h1>

<div class="tagline">
Gateway and proxy server communication failures
</div>

<ins class="adsbygoogle"
     style="display:block;width:100%;"
     data-ad-client="ca-pub-4191744023231140"
     data-ad-slot="7043251880"
     data-ad-format="auto"
     data-full-width-responsive="true"></ins>

<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>

</div>


<div class="section">

<h2>What the 502 Status Code Means</h2>

<p>
The <strong>HTTP 502 Bad Gateway</strong> status code belongs to the
<strong>5xx server error category</strong> of the HTTP specification.
These responses indicate that a server encountered a problem while
processing a request.
</p>

<p>
A <strong>502 Bad Gateway</strong> response occurs when a server acting
as a gateway or proxy receives an invalid or unexpected response from
an upstream server while attempting to fulfill a request.
</p>

<p>
502 errors are frequently seen in environments using reverse proxies
or gateway infrastructure such as <strong>Nginx</strong>,
<strong>Apache</strong>, <strong>Cloudflare</strong>, or cloud load
balancers where multiple servers handle incoming traffic.
</p>

<p>
In modern web architectures, requests often pass through several
infrastructure layers including CDNs, load balancers, reverse proxies,
and API gateways before reaching the application server. If one of
these intermediary systems receives a malformed response or fails to
communicate with the upstream service, it may return a
<strong>502 Bad Gateway</strong> response to the client.
</p>

</div>


<div class="section">

<h2>Common Causes of HTTP 502 Errors</h2>

<ul>

<li>Upstream application servers crashing or restarting</li>
<li>Misconfigured reverse proxy settings</li>
<li>Invalid responses returned by backend services</li>
<li>Network communication failures between servers</li>
<li>Load balancer configuration errors</li>

</ul>

</div>


<div class="section">

<h2>Example of a 502 Response</h2>

<pre>
HTTP/1.1 502 Bad Gateway
Content-Type: text/html
Content-Length: 512
</pre>

<p>
The response is generated by the gateway server rather than the upstream
application that originally handled the request.
</p>

</div>


<div class="section">

<h2>Typical Infrastructure Scenario</h2>

<p>
A common deployment architecture may involve several components handling
incoming requests.
</p>

<pre>
Client → CDN → Load Balancer → Reverse Proxy → Application Server
</pre>

<p>
If the reverse proxy receives an invalid or unexpected response from the
application server, it may return a <strong>502 Bad Gateway</strong> response
to the client.
</p>

</div>


<div class="section">

<h2>How Developers Diagnose 502 Errors</h2>

<ul>

<li>Check upstream server availability</li>
<li>Inspect reverse proxy configuration (Nginx / Apache)</li>
<li>Review load balancer logs</li>
<li>Analyze application server responses</li>
<li>Verify network connectivity between services</li>

</ul>

<p>
Debugging 502 responses often requires analyzing multiple layers of the
infrastructure to determine where the invalid response originated.
</p>

</div>



<div class="section">

<h2>502 vs 504 Gateway Errors</h2>

<p>
Although both errors occur in gateway servers, they represent different
types of failures.
</p>

<ul>

<li><strong>502 Bad Gateway</strong> – the gateway received an invalid response</li>
<li><strong>504 Gateway Timeout</strong> – the gateway did not receive a response in time</li>

</ul>

</div>



<?php include "templates/http-error-codes.php"; ?>



<div class="section">

<h2>Summary</h2>

<p>
The <strong>HTTP 502 Bad Gateway</strong> status code indicates that a gateway
or proxy server received an invalid response from an upstream server while
processing a request.
</p>

<p>
These errors typically occur in distributed systems where multiple servers
communicate with each other, and they often require investigation across
different layers of the infrastructure stack.
</p>

</div>


<div class="footer">
<?php include '../templates/footer.php'; ?>
</div>

</div>

</body>
</html>
